### ISSUE TITLE
Error after updating to PHP 8.0.12

### ISSUE THREAD

**Issue by janekwisniewski86** [salarmehr/cosmopolitan#6] opened 2021-10-21 07:25 UTC
Error: Object of class ResourceBundle could not be converted to string in file /xxx/salarmehr/cosmopolitan/src/Cosmo.php on line 443

![err](https://user-images.githubusercontent.com/41287099/138230679-0ad76fae-23b0-459e-a4a2-1d799c89671a.jpg)

**Comment by salarmehr** [comment] 2021-12-30 15:53
@janekwisniewski86 Do you still see the issue in the newer versions? 8.0.13 and 8.0.14? or even 8.1? 

I'm closing this as it is not a bug of Cosmopolitan.

**Closed by salarmehr** 2021-12-30 15:53 UTC
